version: '3.8'
services:
  db:
    image: "postgres:15"
    environment:
      - POSTGRES_DB=habit-tracker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data/

  db-admin:
    image: "dpage/pgadmin4"
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin


volumes:
  db:
    driver: local
  pgadmin:
    driver: local
